import Header from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid";
import Footer from "@/components/Footer";
import { useRouter } from "next/router";
import { useRef } from "react";
import Body from "@/components/Body";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Body */}
      <Body />  
      {/* Footer */}
      <Footer />
    </>
  );
}
